"""initial migration

Revision ID: 11094ad32a9e
Revises: 
Create Date: 2024-03-15 13:43:38.220137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '11094ad32a9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('team_1', sa.String(), nullable=False),
                    sa.Column('team_2', sa.String(), nullable=False),
                    sa.Column('status', sa.Enum('in process', 'win',
                                                'lose', name='status'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(precision=2), nullable=False),
                    sa.Column('status', sa.Enum('in process', 'win',
                                                'lose', name='status'), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['event_id'], ['events.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("""INSERT INTO events ('team_1', 'team_2', 'status')
               VALUES
               ('Dinamo','Belogorye','in progress'),
               ('Zenit','Shakhter','in progress'),
               ('Trentino','Chivitanova','in progress')""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('events')
    # ### end Alembic commands ###
